/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/modules/app.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/common/src/common_module';
import * as import4 from '@angular/core/src/application_module';
import * as import5 from '@angular/platform-browser/src/browser';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from '@angular/common/src/localization';
import * as import10 from '@angular/core/src/application_init';
import * as import11 from '@angular/core/src/testability/testability';
import * as import12 from '@angular/core/src/application_ref';
import * as import13 from '@angular/core/src/linker/compiler';
import * as import14 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import15 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import16 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import17 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import18 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import19 from '@angular/core/src/linker/view_utils';
import * as import20 from '@angular/platform-browser/src/browser/title';
import * as import21 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import22 from '@angular/forms/src/form_builder';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/common/src/location/location';
import * as import28 from '@angular/router/src/url_tree';
import * as import29 from '@angular/router/src/router_outlet_map';
import * as import30 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import31 from '../../../../src/app/services/GlobalService';
import * as import32 from '../../../../src/app/services/JobService';
import * as import33 from '../../../../src/app/services/TaskService';
import * as import34 from '../../../../src/app/services/ProjectService';
import * as import35 from '@angular/core/src/di/injector';
import * as import36 from '../home/home.component.ngfactory';
import * as import37 from '../job-list/job-list.component.ngfactory';
import * as import38 from '../project-list/project-list.component.ngfactory';
import * as import39 from '../project-view/project-view.component.ngfactory';
import * as import40 from '../task-view/task-view.component.ngfactory';
import * as import41 from '../not-found/not-found.component.ngfactory';
import * as import42 from '../app-main/app-main.component.ngfactory';
import * as import43 from '@angular/core/src/application_tokens';
import * as import44 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import45 from '@angular/platform-browser/src/dom/events/key_events';
import * as import46 from '@angular/core/src/zone/ng_zone';
import * as import47 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import48 from '@angular/common/src/location/platform_location';
import * as import49 from '@angular/common/src/location/location_strategy';
import * as import50 from '../../../../src/app/home/home.component';
import * as import51 from '../../../../src/app/job-list/job-list.component';
import * as import52 from '../../../../src/app/project-list/project-list.component';
import * as import53 from '../../../../src/app/project-view/project-view.component';
import * as import54 from '../../../../src/app/task-view/task-view.component';
import * as import55 from '../../../../src/app/not-found/not-found.component';
import * as import56 from '@angular/router/src/router';
import * as import57 from '@angular/core/src/console';
import * as import58 from '@angular/core/src/i18n/tokens';
import * as import59 from '@angular/core/src/error_handler';
import * as import60 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import61 from '@angular/platform-browser/src/dom/animation_driver';
import * as import62 from '@angular/core/src/render/api';
import * as import63 from '@angular/core/src/security';
import * as import64 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import65 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import66 from '@angular/http/src/interfaces';
import * as import67 from '@angular/http/src/http';
import * as import68 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import69 from '@angular/router/src/router_config_loader';
import * as import70 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _ROUTER_FORROOT_GUARD_0:any;
  _RouterModule_1:import2.RouterModule;
  _CommonModule_2:import3.CommonModule;
  _ApplicationModule_3:import4.ApplicationModule;
  _BrowserModule_4:import5.BrowserModule;
  _InternalFormsSharedModule_5:import6.InternalFormsSharedModule;
  _FormsModule_6:import7.FormsModule;
  _ReactiveFormsModule_7:import7.ReactiveFormsModule;
  _HttpModule_8:import8.HttpModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import9.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import10.ApplicationInitStatus;
  _Testability_14:import11.Testability;
  _ApplicationRef__15:import12.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import13.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import14.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import15.EventManager;
  __DomSharedStylesHost_23:import16.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import17.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import18.DomSanitizerImpl;
  __Sanitizer_28:any;
  __ViewUtils_29:import19.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import20.Title;
  __RadioControlRegistry_34:import21.RadioControlRegistry;
  __FormBuilder_35:import22.FormBuilder;
  __BrowserXhr_36:import23.BrowserXhr;
  __ResponseOptions_37:import24.BaseResponseOptions;
  __XSRFStrategy_38:any;
  __XHRBackend_39:import25.XHRBackend;
  __RequestOptions_40:import26.BaseRequestOptions;
  __Http_41:any;
  __ROUTER_CONFIGURATION_42:any;
  __LocationStrategy_43:any;
  __Location_44:import27.Location;
  __UrlSerializer_45:import28.DefaultUrlSerializer;
  __RouterOutletMap_46:import29.RouterOutletMap;
  __NgModuleFactoryLoader_47:import30.SystemJsNgModuleLoader;
  __ROUTES_48:any[];
  __Router_49:any;
  __ActivatedRoute_50:any;
  __APP_BOOTSTRAP_LISTENER_51:any[];
  __GlobalService_52:import31.GlobalService;
  __JobService_53:import32.JobService;
  __TaskService_54:import33.TaskService;
  __ProjectService_55:import34.ProjectService;
  constructor(parent:import35.Injector) {
    super(parent,[
      import36.HomeComponentNgFactory,
      import37.JobListComponentNgFactory,
      import38.ProjectListComponentNgFactory,
      import39.ProjectViewComponentNgFactory,
      import40.TaskViewComponentNgFactory,
      import41.NotFoundComponentNgFactory,
      import42.AppMainComponentNgFactory
    ]
    ,[import42.AppMainComponentNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import9.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import9.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == (null as any))) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import13.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import13.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = import43._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == (null as any))) { (this.__DOCUMENT_19 = import5._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import14.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_20 = new import14.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import44.DomEventsPlugin(),
      new import45.KeyEventsPlugin(),
      new import14.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import15.EventManager {
    if ((this.__EventManager_22 == (null as any))) { (this.__EventManager_22 = new import15.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import46.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import16.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == (null as any))) { (this.__DomSharedStylesHost_23 = new import16.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == (null as any))) { (this.__AnimationDriver_24 = import5._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import17.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == (null as any))) { (this.__DomRootRenderer_25 = new import17.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == (null as any))) { (this.__RootRenderer_26 = import47._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import47.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import18.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == (null as any))) { (this.__DomSanitizer_27 = new import18.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == (null as any))) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _ViewUtils_29():import19.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import19.ViewUtils(this._RootRenderer_26,this._APP_ID_18,this._Sanitizer_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import4._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import4._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == (null as any))) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import20.Title {
    if ((this.__Title_33 == (null as any))) { (this.__Title_33 = new import20.Title()); }
    return this.__Title_33;
  }
  get _RadioControlRegistry_34():import21.RadioControlRegistry {
    if ((this.__RadioControlRegistry_34 == (null as any))) { (this.__RadioControlRegistry_34 = new import21.RadioControlRegistry()); }
    return this.__RadioControlRegistry_34;
  }
  get _FormBuilder_35():import22.FormBuilder {
    if ((this.__FormBuilder_35 == (null as any))) { (this.__FormBuilder_35 = new import22.FormBuilder()); }
    return this.__FormBuilder_35;
  }
  get _BrowserXhr_36():import23.BrowserXhr {
    if ((this.__BrowserXhr_36 == (null as any))) { (this.__BrowserXhr_36 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_36;
  }
  get _ResponseOptions_37():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_37 == (null as any))) { (this.__ResponseOptions_37 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_37;
  }
  get _XSRFStrategy_38():any {
    if ((this.__XSRFStrategy_38 == (null as any))) { (this.__XSRFStrategy_38 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_38;
  }
  get _XHRBackend_39():import25.XHRBackend {
    if ((this.__XHRBackend_39 == (null as any))) { (this.__XHRBackend_39 = new import25.XHRBackend(this._BrowserXhr_36,this._ResponseOptions_37,this._XSRFStrategy_38)); }
    return this.__XHRBackend_39;
  }
  get _RequestOptions_40():import26.BaseRequestOptions {
    if ((this.__RequestOptions_40 == (null as any))) { (this.__RequestOptions_40 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_40;
  }
  get _Http_41():any {
    if ((this.__Http_41 == (null as any))) { (this.__Http_41 = import8.httpFactory(this._XHRBackend_39,this._RequestOptions_40)); }
    return this.__Http_41;
  }
  get _ROUTER_CONFIGURATION_42():any {
    if ((this.__ROUTER_CONFIGURATION_42 == (null as any))) { (this.__ROUTER_CONFIGURATION_42 = {}); }
    return this.__ROUTER_CONFIGURATION_42;
  }
  get _LocationStrategy_43():any {
    if ((this.__LocationStrategy_43 == (null as any))) { (this.__LocationStrategy_43 = import2.provideLocationStrategy(this.parent.get(import48.PlatformLocation),this.parent.get(import49.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_42)); }
    return this.__LocationStrategy_43;
  }
  get _Location_44():import27.Location {
    if ((this.__Location_44 == (null as any))) { (this.__Location_44 = new import27.Location(this._LocationStrategy_43)); }
    return this.__Location_44;
  }
  get _UrlSerializer_45():import28.DefaultUrlSerializer {
    if ((this.__UrlSerializer_45 == (null as any))) { (this.__UrlSerializer_45 = new import28.DefaultUrlSerializer()); }
    return this.__UrlSerializer_45;
  }
  get _RouterOutletMap_46():import29.RouterOutletMap {
    if ((this.__RouterOutletMap_46 == (null as any))) { (this.__RouterOutletMap_46 = new import29.RouterOutletMap()); }
    return this.__RouterOutletMap_46;
  }
  get _NgModuleFactoryLoader_47():import30.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_47 == (null as any))) { (this.__NgModuleFactoryLoader_47 = new import30.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import30.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_47;
  }
  get _ROUTES_48():any[] {
      if ((this.__ROUTES_48 == (null as any))) { (this.__ROUTES_48 = [[
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'home',
          component: import50.HomeComponent
        }
        ,
        {
          path: 'job/list',
          component: import51.JobListComponent
        }
        ,
        {
          path: 'project/list',
          component: import52.ProjectListComponent
        }
        ,
        {
          path: 'project/view/:project',
          component: import53.ProjectViewComponent
        }
        ,
        {
          path: 'task/view/:project/:task',
          component: import54.TaskViewComponent
        }
        ,
        {
          path: '**',
          component: import55.NotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_48;
  }
  get _Router_49():any {
    if ((this.__Router_49 == (null as any))) { (this.__Router_49 = import2.setupRouter(this._ApplicationRef_16,this._UrlSerializer_45,this._RouterOutletMap_46,this._Location_44,this,this._NgModuleFactoryLoader_47,this._Compiler_17,this._ROUTES_48,this._ROUTER_CONFIGURATION_42)); }
    return this.__Router_49;
  }
  get _ActivatedRoute_50():any {
    if ((this.__ActivatedRoute_50 == (null as any))) { (this.__ActivatedRoute_50 = import2.rootRoute(this._Router_49)); }
    return this.__ActivatedRoute_50;
  }
  get _APP_BOOTSTRAP_LISTENER_51():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_51 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_51 = [import2.initialRouterNavigation(this._Router_49,this._ROUTER_CONFIGURATION_42)]); }
    return this.__APP_BOOTSTRAP_LISTENER_51;
  }
  get _GlobalService_52():import31.GlobalService {
    if ((this.__GlobalService_52 == (null as any))) { (this.__GlobalService_52 = new import31.GlobalService()); }
    return this.__GlobalService_52;
  }
  get _JobService_53():import32.JobService {
    if ((this.__JobService_53 == (null as any))) { (this.__JobService_53 = new import32.JobService(this._Http_41)); }
    return this.__JobService_53;
  }
  get _TaskService_54():import33.TaskService {
    if ((this.__TaskService_54 == (null as any))) { (this.__TaskService_54 = new import33.TaskService(this._Http_41)); }
    return this.__TaskService_54;
  }
  get _ProjectService_55():import34.ProjectService {
    if ((this.__ProjectService_55 == (null as any))) { (this.__ProjectService_55 = new import34.ProjectService(this._Http_41)); }
    return this.__ProjectService_55;
  }
  createInternal():import1.AppModule {
    this._ROUTER_FORROOT_GUARD_0 = import2.provideForRootGuard(this.parent.get(import56.Router,(null as any)));
    this._RouterModule_1 = new import2.RouterModule(this._ROUTER_FORROOT_GUARD_0);
    this._CommonModule_2 = new import3.CommonModule();
    this._ApplicationModule_3 = new import4.ApplicationModule();
    this._BrowserModule_4 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_5 = new import6.InternalFormsSharedModule();
    this._FormsModule_6 = new import7.FormsModule();
    this._ReactiveFormsModule_7 = new import7.ReactiveFormsModule();
    this._HttpModule_8 = new import8.HttpModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import5.errorHandler();
    this._ApplicationInitStatus_13 = new import10.ApplicationInitStatus(this.parent.get(import10.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import11.Testability(this.parent.get(import46.NgZone));
    this._ApplicationRef__15 = new import12.ApplicationRef_(this.parent.get(import46.NgZone),this.parent.get(import57.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import11.TestabilityRegistry,(null as any)),this._Testability_14);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_0; }
    if ((token === import2.RouterModule)) { return this._RouterModule_1; }
    if ((token === import3.CommonModule)) { return this._CommonModule_2; }
    if ((token === import4.ApplicationModule)) { return this._ApplicationModule_3; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_4; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_5; }
    if ((token === import7.FormsModule)) { return this._FormsModule_6; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import8.HttpModule)) { return this._HttpModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import58.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import9.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import59.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import10.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import11.Testability)) { return this._Testability_14; }
    if ((token === import12.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import12.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import13.Compiler)) { return this._Compiler_17; }
    if ((token === import43.APP_ID)) { return this._APP_ID_18; }
    if ((token === import60.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import14.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import15.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import15.EventManager)) { return this._EventManager_22; }
    if ((token === import16.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import61.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import17.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import62.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import18.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import63.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import19.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import64.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import65.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import16.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import20.Title)) { return this._Title_33; }
    if ((token === import21.RadioControlRegistry)) { return this._RadioControlRegistry_34; }
    if ((token === import22.FormBuilder)) { return this._FormBuilder_35; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_36; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_37; }
    if ((token === import66.XSRFStrategy)) { return this._XSRFStrategy_38; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_39; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_40; }
    if ((token === import67.Http)) { return this._Http_41; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_42; }
    if ((token === import49.LocationStrategy)) { return this._LocationStrategy_43; }
    if ((token === import27.Location)) { return this._Location_44; }
    if ((token === import28.UrlSerializer)) { return this._UrlSerializer_45; }
    if ((token === import29.RouterOutletMap)) { return this._RouterOutletMap_46; }
    if ((token === import68.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_47; }
    if ((token === import69.ROUTES)) { return this._ROUTES_48; }
    if ((token === import56.Router)) { return this._Router_49; }
    if ((token === import70.ActivatedRoute)) { return this._ActivatedRoute_50; }
    if ((token === import43.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_51; }
    if ((token === import31.GlobalService)) { return this._GlobalService_52; }
    if ((token === import32.JobService)) { return this._JobService_53; }
    if ((token === import33.TaskService)) { return this._TaskService_54; }
    if ((token === import34.ProjectService)) { return this._ProjectService_55; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);