/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/modules/app.module';
import * as import2 from '@angular/router/src/router_module';
import * as import3 from '@angular/common/src/common_module';
import * as import4 from '@angular/core/src/application_module';
import * as import5 from '@angular/platform-browser/src/browser';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from 'ng2-charts/components/charts/charts';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/forms/src/form_builder';
import * as import24 from '@angular/http/src/backends/browser_xhr';
import * as import25 from '@angular/http/src/base_response_options';
import * as import26 from '@angular/http/src/backends/xhr_backend';
import * as import27 from '@angular/http/src/base_request_options';
import * as import28 from '@angular/common/src/location/location';
import * as import29 from '@angular/router/src/url_tree';
import * as import30 from '@angular/router/src/router_outlet_map';
import * as import31 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import32 from '@angular/router/src/router_preloader';
import * as import33 from '../../../../src/app/services/GlobalService';
import * as import34 from '../../../../src/app/services/JobService';
import * as import35 from '../../../../src/app/services/TaskService';
import * as import36 from '../../../../src/app/services/ProjectService';
import * as import37 from '@angular/core/src/di/injector';
import * as import38 from '../home/home.component.ngfactory';
import * as import39 from '../job-list/job-list.component.ngfactory';
import * as import40 from '../project-list/project-list.component.ngfactory';
import * as import41 from '../project-view/project-view.component.ngfactory';
import * as import42 from '../task-view/task-view.component.ngfactory';
import * as import43 from '../not-found/not-found.component.ngfactory';
import * as import44 from '../app-main/app-main.component.ngfactory';
import * as import45 from '@angular/core/src/application_tokens';
import * as import46 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import47 from '@angular/platform-browser/src/dom/events/key_events';
import * as import48 from '@angular/core/src/zone/ng_zone';
import * as import49 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import50 from '@angular/common/src/location/platform_location';
import * as import51 from '@angular/common/src/location/location_strategy';
import * as import52 from '../../../../src/app/home/home.component';
import * as import53 from '../../../../src/app/job-list/job-list.component';
import * as import54 from '../../../../src/app/project-list/project-list.component';
import * as import55 from '../../../../src/app/project-view/project-view.component';
import * as import56 from '../../../../src/app/task-view/task-view.component';
import * as import57 from '../../../../src/app/not-found/not-found.component';
import * as import58 from '@angular/router/src/router';
import * as import59 from '@angular/core/src/console';
import * as import60 from '@angular/core/src/i18n/tokens';
import * as import61 from '@angular/core/src/error_handler';
import * as import62 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import63 from '@angular/platform-browser/src/dom/animation_driver';
import * as import64 from '@angular/core/src/render/api';
import * as import65 from '@angular/core/src/security';
import * as import66 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import67 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import68 from '@angular/http/src/interfaces';
import * as import69 from '@angular/http/src/http';
import * as import70 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import71 from '@angular/router/src/router_config_loader';
import * as import72 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _ROUTER_FORROOT_GUARD_0:any;
  _RouterModule_1:import2.RouterModule;
  _CommonModule_2:import3.CommonModule;
  _ApplicationModule_3:import4.ApplicationModule;
  _BrowserModule_4:import5.BrowserModule;
  _InternalFormsSharedModule_5:import6.InternalFormsSharedModule;
  _FormsModule_6:import7.FormsModule;
  _ReactiveFormsModule_7:import7.ReactiveFormsModule;
  _HttpModule_8:import8.HttpModule;
  _ChartsModule_9:import9.ChartsModule;
  _AppModule_10:import1.AppModule;
  __LOCALE_ID_11:any;
  __NgLocalization_12:import10.NgLocaleLocalization;
  _ErrorHandler_13:any;
  _ApplicationInitStatus_14:import11.ApplicationInitStatus;
  _Testability_15:import12.Testability;
  _ApplicationRef__16:import13.ApplicationRef_;
  __ApplicationRef_17:any;
  __Compiler_18:import14.Compiler;
  __APP_ID_19:any;
  __DOCUMENT_20:any;
  __HAMMER_GESTURE_CONFIG_21:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_22:any[];
  __EventManager_23:import16.EventManager;
  __DomSharedStylesHost_24:import17.DomSharedStylesHost;
  __AnimationDriver_25:any;
  __DomRootRenderer_26:import18.DomRootRenderer_;
  __RootRenderer_27:any;
  __DomSanitizer_28:import19.DomSanitizerImpl;
  __Sanitizer_29:any;
  __ViewUtils_30:import20.ViewUtils;
  __IterableDiffers_31:any;
  __KeyValueDiffers_32:any;
  __SharedStylesHost_33:any;
  __Title_34:import21.Title;
  __RadioControlRegistry_35:import22.RadioControlRegistry;
  __FormBuilder_36:import23.FormBuilder;
  __BrowserXhr_37:import24.BrowserXhr;
  __ResponseOptions_38:import25.BaseResponseOptions;
  __XSRFStrategy_39:any;
  __XHRBackend_40:import26.XHRBackend;
  __RequestOptions_41:import27.BaseRequestOptions;
  __Http_42:any;
  __ROUTER_CONFIGURATION_43:any;
  __LocationStrategy_44:any;
  __Location_45:import28.Location;
  __UrlSerializer_46:import29.DefaultUrlSerializer;
  __RouterOutletMap_47:import30.RouterOutletMap;
  __NgModuleFactoryLoader_48:import31.SystemJsNgModuleLoader;
  __ROUTES_49:any[];
  __Router_50:any;
  __ActivatedRoute_51:any;
  _NoPreloading_52:import32.NoPreloading;
  _PreloadingStrategy_53:any;
  _RouterPreloader_54:import32.RouterPreloader;
  __PreloadAllModules_55:import32.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_56:any[];
  __GlobalService_57:import33.GlobalService;
  __JobService_58:import34.JobService;
  __TaskService_59:import35.TaskService;
  __ProjectService_60:import36.ProjectService;
  constructor(parent:import37.Injector) {
    super(parent,[
      import38.HomeComponentNgFactory,
      import39.JobListComponentNgFactory,
      import40.ProjectListComponentNgFactory,
      import41.ProjectViewComponentNgFactory,
      import42.TaskViewComponentNgFactory,
      import43.NotFoundComponentNgFactory,
      import44.AppMainComponentNgFactory
    ]
    ,[import44.AppMainComponentNgFactory]);
  }
  get _LOCALE_ID_11():any {
    if ((this.__LOCALE_ID_11 == (null as any))) { (this.__LOCALE_ID_11 = 'en-US'); }
    return this.__LOCALE_ID_11;
  }
  get _NgLocalization_12():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_12 == (null as any))) { (this.__NgLocalization_12 = new import10.NgLocaleLocalization(this._LOCALE_ID_11)); }
    return this.__NgLocalization_12;
  }
  get _ApplicationRef_17():any {
    if ((this.__ApplicationRef_17 == (null as any))) { (this.__ApplicationRef_17 = this._ApplicationRef__16); }
    return this.__ApplicationRef_17;
  }
  get _Compiler_18():import14.Compiler {
    if ((this.__Compiler_18 == (null as any))) { (this.__Compiler_18 = new import14.Compiler()); }
    return this.__Compiler_18;
  }
  get _APP_ID_19():any {
    if ((this.__APP_ID_19 == (null as any))) { (this.__APP_ID_19 = import45._appIdRandomProviderFactory()); }
    return this.__APP_ID_19;
  }
  get _DOCUMENT_20():any {
    if ((this.__DOCUMENT_20 == (null as any))) { (this.__DOCUMENT_20 = import5._document()); }
    return this.__DOCUMENT_20;
  }
  get _HAMMER_GESTURE_CONFIG_21():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_21 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_21 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_21;
  }
  get _EVENT_MANAGER_PLUGINS_22():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_22 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_22 = [
      new import46.DomEventsPlugin(),
      new import47.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_21)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_22;
  }
  get _EventManager_23():import16.EventManager {
    if ((this.__EventManager_23 == (null as any))) { (this.__EventManager_23 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_22,this.parent.get(import48.NgZone))); }
    return this.__EventManager_23;
  }
  get _DomSharedStylesHost_24():import17.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_24 == (null as any))) { (this.__DomSharedStylesHost_24 = new import17.DomSharedStylesHost(this._DOCUMENT_20)); }
    return this.__DomSharedStylesHost_24;
  }
  get _AnimationDriver_25():any {
    if ((this.__AnimationDriver_25 == (null as any))) { (this.__AnimationDriver_25 = import5._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_25;
  }
  get _DomRootRenderer_26():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_26 == (null as any))) { (this.__DomRootRenderer_26 = new import18.DomRootRenderer_(this._DOCUMENT_20,this._EventManager_23,this._DomSharedStylesHost_24,this._AnimationDriver_25)); }
    return this.__DomRootRenderer_26;
  }
  get _RootRenderer_27():any {
    if ((this.__RootRenderer_27 == (null as any))) { (this.__RootRenderer_27 = import49._createConditionalRootRenderer(this._DomRootRenderer_26,this.parent.get(import49.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_27;
  }
  get _DomSanitizer_28():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_28 == (null as any))) { (this.__DomSanitizer_28 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_28;
  }
  get _Sanitizer_29():any {
    if ((this.__Sanitizer_29 == (null as any))) { (this.__Sanitizer_29 = this._DomSanitizer_28); }
    return this.__Sanitizer_29;
  }
  get _ViewUtils_30():import20.ViewUtils {
    if ((this.__ViewUtils_30 == (null as any))) { (this.__ViewUtils_30 = new import20.ViewUtils(this._RootRenderer_27,this._APP_ID_19,this._Sanitizer_29)); }
    return this.__ViewUtils_30;
  }
  get _IterableDiffers_31():any {
    if ((this.__IterableDiffers_31 == (null as any))) { (this.__IterableDiffers_31 = import4._iterableDiffersFactory()); }
    return this.__IterableDiffers_31;
  }
  get _KeyValueDiffers_32():any {
    if ((this.__KeyValueDiffers_32 == (null as any))) { (this.__KeyValueDiffers_32 = import4._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_32;
  }
  get _SharedStylesHost_33():any {
    if ((this.__SharedStylesHost_33 == (null as any))) { (this.__SharedStylesHost_33 = this._DomSharedStylesHost_24); }
    return this.__SharedStylesHost_33;
  }
  get _Title_34():import21.Title {
    if ((this.__Title_34 == (null as any))) { (this.__Title_34 = new import21.Title()); }
    return this.__Title_34;
  }
  get _RadioControlRegistry_35():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_35 == (null as any))) { (this.__RadioControlRegistry_35 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_35;
  }
  get _FormBuilder_36():import23.FormBuilder {
    if ((this.__FormBuilder_36 == (null as any))) { (this.__FormBuilder_36 = new import23.FormBuilder()); }
    return this.__FormBuilder_36;
  }
  get _BrowserXhr_37():import24.BrowserXhr {
    if ((this.__BrowserXhr_37 == (null as any))) { (this.__BrowserXhr_37 = new import24.BrowserXhr()); }
    return this.__BrowserXhr_37;
  }
  get _ResponseOptions_38():import25.BaseResponseOptions {
    if ((this.__ResponseOptions_38 == (null as any))) { (this.__ResponseOptions_38 = new import25.BaseResponseOptions()); }
    return this.__ResponseOptions_38;
  }
  get _XSRFStrategy_39():any {
    if ((this.__XSRFStrategy_39 == (null as any))) { (this.__XSRFStrategy_39 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_39;
  }
  get _XHRBackend_40():import26.XHRBackend {
    if ((this.__XHRBackend_40 == (null as any))) { (this.__XHRBackend_40 = new import26.XHRBackend(this._BrowserXhr_37,this._ResponseOptions_38,this._XSRFStrategy_39)); }
    return this.__XHRBackend_40;
  }
  get _RequestOptions_41():import27.BaseRequestOptions {
    if ((this.__RequestOptions_41 == (null as any))) { (this.__RequestOptions_41 = new import27.BaseRequestOptions()); }
    return this.__RequestOptions_41;
  }
  get _Http_42():any {
    if ((this.__Http_42 == (null as any))) { (this.__Http_42 = import8.httpFactory(this._XHRBackend_40,this._RequestOptions_41)); }
    return this.__Http_42;
  }
  get _ROUTER_CONFIGURATION_43():any {
    if ((this.__ROUTER_CONFIGURATION_43 == (null as any))) { (this.__ROUTER_CONFIGURATION_43 = {}); }
    return this.__ROUTER_CONFIGURATION_43;
  }
  get _LocationStrategy_44():any {
    if ((this.__LocationStrategy_44 == (null as any))) { (this.__LocationStrategy_44 = import2.provideLocationStrategy(this.parent.get(import50.PlatformLocation),this.parent.get(import51.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_43)); }
    return this.__LocationStrategy_44;
  }
  get _Location_45():import28.Location {
    if ((this.__Location_45 == (null as any))) { (this.__Location_45 = new import28.Location(this._LocationStrategy_44)); }
    return this.__Location_45;
  }
  get _UrlSerializer_46():import29.DefaultUrlSerializer {
    if ((this.__UrlSerializer_46 == (null as any))) { (this.__UrlSerializer_46 = new import29.DefaultUrlSerializer()); }
    return this.__UrlSerializer_46;
  }
  get _RouterOutletMap_47():import30.RouterOutletMap {
    if ((this.__RouterOutletMap_47 == (null as any))) { (this.__RouterOutletMap_47 = new import30.RouterOutletMap()); }
    return this.__RouterOutletMap_47;
  }
  get _NgModuleFactoryLoader_48():import31.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_48 == (null as any))) { (this.__NgModuleFactoryLoader_48 = new import31.SystemJsNgModuleLoader(this._Compiler_18,this.parent.get(import31.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_48;
  }
  get _ROUTES_49():any[] {
      if ((this.__ROUTES_49 == (null as any))) { (this.__ROUTES_49 = [[
        {
          path: '',
          redirectTo: '/home',
          pathMatch: 'full'
        }
        ,
        {
          path: 'home',
          component: import52.HomeComponent
        }
        ,
        {
          path: 'job/list',
          component: import53.JobListComponent
        }
        ,
        {
          path: 'project/list',
          component: import54.ProjectListComponent
        }
        ,
        {
          path: 'project/view/:project',
          component: import55.ProjectViewComponent
        }
        ,
        {
          path: 'task/view/:project/:task',
          component: import56.TaskViewComponent
        }
        ,
        {
          path: '**',
          component: import57.NotFoundComponent
        }

      ]
    ]); }
    return this.__ROUTES_49;
  }
  get _Router_50():any {
    if ((this.__Router_50 == (null as any))) { (this.__Router_50 = import2.setupRouter(this._ApplicationRef_17,this._UrlSerializer_46,this._RouterOutletMap_47,this._Location_45,this,this._NgModuleFactoryLoader_48,this._Compiler_18,this._ROUTES_49,this._ROUTER_CONFIGURATION_43)); }
    return this.__Router_50;
  }
  get _ActivatedRoute_51():any {
    if ((this.__ActivatedRoute_51 == (null as any))) { (this.__ActivatedRoute_51 = import2.rootRoute(this._Router_50)); }
    return this.__ActivatedRoute_51;
  }
  get _PreloadAllModules_55():import32.PreloadAllModules {
    if ((this.__PreloadAllModules_55 == (null as any))) { (this.__PreloadAllModules_55 = new import32.PreloadAllModules()); }
    return this.__PreloadAllModules_55;
  }
  get _APP_BOOTSTRAP_LISTENER_56():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_56 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_56 = [import2.initialRouterNavigation(this._Router_50,this._ApplicationRef_17,this._RouterPreloader_54,this._ROUTER_CONFIGURATION_43)]); }
    return this.__APP_BOOTSTRAP_LISTENER_56;
  }
  get _GlobalService_57():import33.GlobalService {
    if ((this.__GlobalService_57 == (null as any))) { (this.__GlobalService_57 = new import33.GlobalService()); }
    return this.__GlobalService_57;
  }
  get _JobService_58():import34.JobService {
    if ((this.__JobService_58 == (null as any))) { (this.__JobService_58 = new import34.JobService(this._Http_42)); }
    return this.__JobService_58;
  }
  get _TaskService_59():import35.TaskService {
    if ((this.__TaskService_59 == (null as any))) { (this.__TaskService_59 = new import35.TaskService(this._Http_42)); }
    return this.__TaskService_59;
  }
  get _ProjectService_60():import36.ProjectService {
    if ((this.__ProjectService_60 == (null as any))) { (this.__ProjectService_60 = new import36.ProjectService(this._Http_42)); }
    return this.__ProjectService_60;
  }
  createInternal():import1.AppModule {
    this._ROUTER_FORROOT_GUARD_0 = import2.provideForRootGuard(this.parent.get(import58.Router,(null as any)));
    this._RouterModule_1 = new import2.RouterModule(this._ROUTER_FORROOT_GUARD_0);
    this._CommonModule_2 = new import3.CommonModule();
    this._ApplicationModule_3 = new import4.ApplicationModule();
    this._BrowserModule_4 = new import5.BrowserModule(this.parent.get(import5.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_5 = new import6.InternalFormsSharedModule();
    this._FormsModule_6 = new import7.FormsModule();
    this._ReactiveFormsModule_7 = new import7.ReactiveFormsModule();
    this._HttpModule_8 = new import8.HttpModule();
    this._ChartsModule_9 = new import9.ChartsModule();
    this._AppModule_10 = new import1.AppModule();
    this._ErrorHandler_13 = import5.errorHandler();
    this._ApplicationInitStatus_14 = new import11.ApplicationInitStatus(this.parent.get(import11.APP_INITIALIZER,(null as any)));
    this._Testability_15 = new import12.Testability(this.parent.get(import48.NgZone));
    this._ApplicationRef__16 = new import13.ApplicationRef_(this.parent.get(import48.NgZone),this.parent.get(import59.Console),this,this._ErrorHandler_13,this,this._ApplicationInitStatus_14,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_15);
    this._NoPreloading_52 = new import32.NoPreloading();
    this._PreloadingStrategy_53 = this._NoPreloading_52;
    this._RouterPreloader_54 = new import32.RouterPreloader(this._Router_50,this._NgModuleFactoryLoader_48,this._Compiler_18,this,this._PreloadingStrategy_53);
    return this._AppModule_10;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_0; }
    if ((token === import2.RouterModule)) { return this._RouterModule_1; }
    if ((token === import3.CommonModule)) { return this._CommonModule_2; }
    if ((token === import4.ApplicationModule)) { return this._ApplicationModule_3; }
    if ((token === import5.BrowserModule)) { return this._BrowserModule_4; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_5; }
    if ((token === import7.FormsModule)) { return this._FormsModule_6; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import8.HttpModule)) { return this._HttpModule_8; }
    if ((token === import9.ChartsModule)) { return this._ChartsModule_9; }
    if ((token === import1.AppModule)) { return this._AppModule_10; }
    if ((token === import60.LOCALE_ID)) { return this._LOCALE_ID_11; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_12; }
    if ((token === import61.ErrorHandler)) { return this._ErrorHandler_13; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_14; }
    if ((token === import12.Testability)) { return this._Testability_15; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__16; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_17; }
    if ((token === import14.Compiler)) { return this._Compiler_18; }
    if ((token === import45.APP_ID)) { return this._APP_ID_19; }
    if ((token === import62.DOCUMENT)) { return this._DOCUMENT_20; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_21; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_22; }
    if ((token === import16.EventManager)) { return this._EventManager_23; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_24; }
    if ((token === import63.AnimationDriver)) { return this._AnimationDriver_25; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_26; }
    if ((token === import64.RootRenderer)) { return this._RootRenderer_27; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_28; }
    if ((token === import65.Sanitizer)) { return this._Sanitizer_29; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_30; }
    if ((token === import66.IterableDiffers)) { return this._IterableDiffers_31; }
    if ((token === import67.KeyValueDiffers)) { return this._KeyValueDiffers_32; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_33; }
    if ((token === import21.Title)) { return this._Title_34; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_35; }
    if ((token === import23.FormBuilder)) { return this._FormBuilder_36; }
    if ((token === import24.BrowserXhr)) { return this._BrowserXhr_37; }
    if ((token === import25.ResponseOptions)) { return this._ResponseOptions_38; }
    if ((token === import68.XSRFStrategy)) { return this._XSRFStrategy_39; }
    if ((token === import26.XHRBackend)) { return this._XHRBackend_40; }
    if ((token === import27.RequestOptions)) { return this._RequestOptions_41; }
    if ((token === import69.Http)) { return this._Http_42; }
    if ((token === import2.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_43; }
    if ((token === import51.LocationStrategy)) { return this._LocationStrategy_44; }
    if ((token === import28.Location)) { return this._Location_45; }
    if ((token === import29.UrlSerializer)) { return this._UrlSerializer_46; }
    if ((token === import30.RouterOutletMap)) { return this._RouterOutletMap_47; }
    if ((token === import70.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_48; }
    if ((token === import71.ROUTES)) { return this._ROUTES_49; }
    if ((token === import58.Router)) { return this._Router_50; }
    if ((token === import72.ActivatedRoute)) { return this._ActivatedRoute_51; }
    if ((token === import32.NoPreloading)) { return this._NoPreloading_52; }
    if ((token === import32.PreloadingStrategy)) { return this._PreloadingStrategy_53; }
    if ((token === import32.RouterPreloader)) { return this._RouterPreloader_54; }
    if ((token === import32.PreloadAllModules)) { return this._PreloadAllModules_55; }
    if ((token === import45.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_56; }
    if ((token === import33.GlobalService)) { return this._GlobalService_57; }
    if ((token === import34.JobService)) { return this._JobService_58; }
    if ((token === import35.TaskService)) { return this._TaskService_59; }
    if ((token === import36.ProjectService)) { return this._ProjectService_60; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__16.ngOnDestroy();
    this._RouterPreloader_54.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);