/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.footer[_ngcontent-%COMP%] {\n	height: 60px;\n	background-color: #f5f5f5;\n	border-top: 1px solid #ddd;\n	padding-top: 20px;\n}\n\n.no-footer[_ngcontent-%COMP%] {\n	display: none;\n}'];