/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../src/app/job-list/job-list.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../src/app/services/GlobalService';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './job-list.component.css.shim';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '../../../../src/app/pipes/timestampFormat';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from '@angular/common/src/directives/ng_switch';
import * as import19 from '@angular/core/src/security';
import * as import20 from 'ng2-charts/components/charts/charts';
import * as import21 from '../../../node_modules/ng2-charts/components/charts/charts.ngfactory';
import * as import22 from '@angular/core/src/linker/element_ref';
var renderType_JobListComponent_Host:import0.RenderComponentType = (null as any);
class _View_JobListComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _JobListComponent_0_4:import3.JobListComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent_Host0,renderType_JobListComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('job-list',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_JobListComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._JobListComponent_0_4 = new import3.JobListComponent(this.parentInjector.get(import8.GlobalService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._JobListComponent_0_4,[],compView_0);
    compView_0.create(this._JobListComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.JobListComponent) && (0 === requestNodeIndex))) { return this._JobListComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._JobListComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_JobListComponent_Host === (null as any))) { (renderType_JobListComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_JobListComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const JobListComponentNgFactory:import11.ComponentFactory<import3.JobListComponent> = new import11.ComponentFactory<import3.JobListComponent>('job-list',viewFactory_JobListComponent_Host0,import3.JobListComponent);
const styles_JobListComponent:any[] = [import12.styles];
var renderType_JobListComponent:import0.RenderComponentType = (null as any);
class _View_JobListComponent0 extends import1.AppView<import3.JobListComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import13.NgIf;
  _text_19:any;
  _anchor_20:any;
  /*private*/ _appEl_20:import2.AppElement;
  _TemplateRef_20_5:any;
  _NgIf_20_6:import13.NgIf;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgIf_22_6:import13.NgIf;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import13.NgIf;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _anchor_29:any;
  /*private*/ _appEl_29:import2.AppElement;
  _TemplateRef_29_5:any;
  _NgIf_29_6:import13.NgIf;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgIf_31_6:import13.NgIf;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import13.NgIf;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgIf_35_6:import13.NgIf;
  _text_36:any;
  _text_37:any;
  /*private*/ _expr_1:any;
  _pipe_timestampFormat_0:import14.TimestampFormat;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent0,renderType_JobListComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','job-list');
    this._text_1 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','col-md-8 col-lg-8');
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_5 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','panel panel-default');
    this.renderer.setElementAttribute(this._el_5,'id','options-container');
    this._text_6 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','panel-body');
    this._text_8 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','options-container-title');
    this._text_10 = this.renderer.createText(this._el_9,'Job List',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_12,'type','button');
    this._text_13 = this.renderer.createText(this._el_12,'Back',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._text_16 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._text_17 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_18 = new import2.AppElement(18,2,this,this._anchor_18);
    this._TemplateRef_18_5 = new import15.TemplateRef_(this._appEl_18,viewFactory_JobListComponent1);
    this._NgIf_18_6 = new import13.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._anchor_20 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_20 = new import2.AppElement(20,2,this,this._anchor_20);
    this._TemplateRef_20_5 = new import15.TemplateRef_(this._appEl_20,viewFactory_JobListComponent13);
    this._NgIf_20_6 = new import13.NgIf(this._appEl_20.vcRef,this._TemplateRef_20_5);
    this._text_21 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_22 = new import2.AppElement(22,2,this,this._anchor_22);
    this._TemplateRef_22_5 = new import15.TemplateRef_(this._appEl_22,viewFactory_JobListComponent14);
    this._NgIf_22_6 = new import13.NgIf(this._appEl_22.vcRef,this._TemplateRef_22_5);
    this._text_23 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_24 = new import2.AppElement(24,2,this,this._anchor_24);
    this._TemplateRef_24_5 = new import15.TemplateRef_(this._appEl_24,viewFactory_JobListComponent15);
    this._NgIf_24_6 = new import13.NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_27 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','col-md-4 col-lg-4');
    this._text_28 = this.renderer.createText(this._el_27,'\n		',(null as any));
    this._anchor_29 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_29 = new import2.AppElement(29,27,this,this._anchor_29);
    this._TemplateRef_29_5 = new import15.TemplateRef_(this._appEl_29,viewFactory_JobListComponent16);
    this._NgIf_29_6 = new import13.NgIf(this._appEl_29.vcRef,this._TemplateRef_29_5);
    this._text_30 = this.renderer.createText(this._el_27,'\n\n		',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_31 = new import2.AppElement(31,27,this,this._anchor_31);
    this._TemplateRef_31_5 = new import15.TemplateRef_(this._appEl_31,viewFactory_JobListComponent17);
    this._NgIf_31_6 = new import13.NgIf(this._appEl_31.vcRef,this._TemplateRef_31_5);
    this._text_32 = this.renderer.createText(this._el_27,'\n\n		',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_33 = new import2.AppElement(33,27,this,this._anchor_33);
    this._TemplateRef_33_5 = new import15.TemplateRef_(this._appEl_33,viewFactory_JobListComponent18);
    this._NgIf_33_6 = new import13.NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_27,'\n\n		',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_27,(null as any));
    this._appEl_35 = new import2.AppElement(35,27,this,this._anchor_35);
    this._TemplateRef_35_5 = new import15.TemplateRef_(this._appEl_35,viewFactory_JobListComponent19);
    this._NgIf_35_6 = new import13.NgIf(this._appEl_35.vcRef,this._TemplateRef_35_5);
    this._text_36 = this.renderer.createText(this._el_27,'\n	',(null as any));
    this._text_37 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._pipe_timestampFormat_0 = new import14.TimestampFormat();
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._anchor_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._anchor_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._text_37
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import13.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import15.TemplateRef) && (20 === requestNodeIndex))) { return this._TemplateRef_20_5; }
    if (((token === import13.NgIf) && (20 === requestNodeIndex))) { return this._NgIf_20_6; }
    if (((token === import15.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import13.NgIf) && (22 === requestNodeIndex))) { return this._NgIf_22_6; }
    if (((token === import15.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import13.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6; }
    if (((token === import15.TemplateRef) && (29 === requestNodeIndex))) { return this._TemplateRef_29_5; }
    if (((token === import13.NgIf) && (29 === requestNodeIndex))) { return this._NgIf_29_6; }
    if (((token === import15.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import13.NgIf) && (31 === requestNodeIndex))) { return this._NgIf_31_6; }
    if (((token === import15.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import13.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6; }
    if (((token === import15.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import13.NgIf) && (35 === requestNodeIndex))) { return this._NgIf_35_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.showData;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_18_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.showEmptyData;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_20_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.showError;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_22_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.showLoading;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_24_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.showData;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_29_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.showEmptyData;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgIf_31_6.ngIf = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.showError;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_33_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.showLoading;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_35_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.back()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_JobListComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.JobListComponent> {
  if ((renderType_JobListComponent === (null as any))) { (renderType_JobListComponent = viewUtils.createRenderComponentType('/Users/paulo/Documents/workspaces/go/src/github.com/prsolucoes/goci/web-app/src/app/job-list/job-list.component.html',0,import10.ViewEncapsulation.Emulated,styles_JobListComponent,{})); }
  return new _View_JobListComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _TemplateRef_4_5:any;
  _NgFor_4_6:import16.NgFor;
  _text_5:any;
  _text_6:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent1,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','list-group');
    this.renderer.setElementAttribute(this._el_2,'id','job-list');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._anchor_4);
    this._TemplateRef_4_5 = new import15.TemplateRef_(this._appEl_4,viewFactory_JobListComponent2);
    this._NgFor_4_6 = new import16.NgFor(this._appEl_4.vcRef,this._TemplateRef_4_5,this.parent.parentInjector.get(import17.IterableDiffers),this.parent.ref);
    this._text_5 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5,
      this._text_6
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import16.NgFor) && (4 === requestNodeIndex))) { return this._NgFor_4_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.jobList;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_4_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_4_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_4_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _NgSwitch_39_3:import18.NgSwitch;
  _text_40:any;
  _anchor_41:any;
  /*private*/ _appEl_41:import2.AppElement;
  _TemplateRef_41_5:any;
  _NgSwitchCase_41_6:import18.NgSwitchCase;
  _text_42:any;
  _anchor_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _TemplateRef_43_5:any;
  _NgSwitchCase_43_6:import18.NgSwitchCase;
  _text_44:any;
  _anchor_45:any;
  /*private*/ _appEl_45:import2.AppElement;
  _TemplateRef_45_5:any;
  _NgSwitchCase_45_6:import18.NgSwitchCase;
  _text_46:any;
  _anchor_47:any;
  /*private*/ _appEl_47:import2.AppElement;
  _TemplateRef_47_5:any;
  _NgSwitchCase_47_6:import18.NgSwitchCase;
  _text_48:any;
  _anchor_49:any;
  /*private*/ _appEl_49:import2.AppElement;
  _TemplateRef_49_5:any;
  _NgSwitchDefault_49_6:import18.NgSwitchDefault;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _NgSwitch_60_3:import18.NgSwitch;
  _text_61:any;
  _anchor_62:any;
  /*private*/ _appEl_62:import2.AppElement;
  _TemplateRef_62_5:any;
  _NgSwitchCase_62_6:import18.NgSwitchCase;
  _text_63:any;
  _anchor_64:any;
  /*private*/ _appEl_64:import2.AppElement;
  _TemplateRef_64_5:any;
  _NgSwitchCase_64_6:import18.NgSwitchCase;
  _text_65:any;
  _anchor_66:any;
  /*private*/ _appEl_66:import2.AppElement;
  _TemplateRef_66_5:any;
  _NgSwitchCase_66_6:import18.NgSwitchCase;
  _text_67:any;
  _anchor_68:any;
  /*private*/ _appEl_68:import2.AppElement;
  _TemplateRef_68_5:any;
  _NgSwitchCase_68_6:import18.NgSwitchCase;
  _text_69:any;
  _anchor_70:any;
  /*private*/ _appEl_70:import2.AppElement;
  _TemplateRef_70_5:any;
  _NgSwitchDefault_70_6:import18.NgSwitchDefault;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  _pipe_timestampFormat_0_0:any;
  /*private*/ _expr_4:any;
  _pipe_timestampFormat_0_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent2,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','job-row list-group-item');
    this._text_1 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','list-group-item-heading');
    this._text_3 = this.renderer.createText(this._el_2,'\n						',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'a',(null as any));
    this.renderer.setElementAttribute(this._el_4,'href','javascript:void(0);');
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n					',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n					',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','list-group-item-text');
    this._text_9 = this.renderer.createText(this._el_8,'\n						',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'div',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n							',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'strong',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Job: ',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n						',(null as any));
    this._el_16 = this.renderer.createElement(this._el_8,'div',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n							',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'strong',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Created at:',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_8,'\n						',(null as any));
    this._el_22 = this.renderer.createElement(this._el_8,'div',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n							',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'strong',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Started at:',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_27 = this.renderer.createText(this._el_8,'\n						',(null as any));
    this._el_28 = this.renderer.createElement(this._el_8,'div',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n							',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'strong',(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Duration:',(null as any));
    this._text_32 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_33 = this.renderer.createText(this._el_8,'\n						',(null as any));
    this._el_34 = this.renderer.createElement(this._el_8,'div',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n							',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'strong',(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Status:',(null as any));
    this._text_38 = this.renderer.createText(this._el_34,'\n							',(null as any));
    this._el_39 = this.renderer.createElement(this._el_34,'span',(null as any));
    this._NgSwitch_39_3 = new import18.NgSwitch();
    this._text_40 = this.renderer.createText(this._el_39,'\n							',(null as any));
    this._anchor_41 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_41 = new import2.AppElement(41,39,this,this._anchor_41);
    this._TemplateRef_41_5 = new import15.TemplateRef_(this._appEl_41,viewFactory_JobListComponent3);
    this._NgSwitchCase_41_6 = new import18.NgSwitchCase(this._appEl_41.vcRef,this._TemplateRef_41_5,this._NgSwitch_39_3);
    this._text_42 = this.renderer.createText(this._el_39,'\n							',(null as any));
    this._anchor_43 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_43 = new import2.AppElement(43,39,this,this._anchor_43);
    this._TemplateRef_43_5 = new import15.TemplateRef_(this._appEl_43,viewFactory_JobListComponent4);
    this._NgSwitchCase_43_6 = new import18.NgSwitchCase(this._appEl_43.vcRef,this._TemplateRef_43_5,this._NgSwitch_39_3);
    this._text_44 = this.renderer.createText(this._el_39,'\n							',(null as any));
    this._anchor_45 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_45 = new import2.AppElement(45,39,this,this._anchor_45);
    this._TemplateRef_45_5 = new import15.TemplateRef_(this._appEl_45,viewFactory_JobListComponent5);
    this._NgSwitchCase_45_6 = new import18.NgSwitchCase(this._appEl_45.vcRef,this._TemplateRef_45_5,this._NgSwitch_39_3);
    this._text_46 = this.renderer.createText(this._el_39,'\n							',(null as any));
    this._anchor_47 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_47 = new import2.AppElement(47,39,this,this._anchor_47);
    this._TemplateRef_47_5 = new import15.TemplateRef_(this._appEl_47,viewFactory_JobListComponent6);
    this._NgSwitchCase_47_6 = new import18.NgSwitchCase(this._appEl_47.vcRef,this._TemplateRef_47_5,this._NgSwitch_39_3);
    this._text_48 = this.renderer.createText(this._el_39,'\n							',(null as any));
    this._anchor_49 = this.renderer.createTemplateAnchor(this._el_39,(null as any));
    this._appEl_49 = new import2.AppElement(49,39,this,this._anchor_49);
    this._TemplateRef_49_5 = new import15.TemplateRef_(this._appEl_49,viewFactory_JobListComponent7);
    this._NgSwitchDefault_49_6 = new import18.NgSwitchDefault(this._appEl_49.vcRef,this._TemplateRef_49_5,this._NgSwitch_39_3);
    this._text_50 = this.renderer.createText(this._el_39,'\n						',(null as any));
    this._text_51 = this.renderer.createText(this._el_34,'\n						',(null as any));
    this._text_52 = this.renderer.createText(this._el_8,'\n						',(null as any));
    this._el_53 = this.renderer.createElement(this._el_8,'div',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'\n							',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'strong',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,'Progress:',(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n							',(null as any));
    this._el_58 = this.renderer.createElement(this._el_53,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','progress');
    this._text_59 = this.renderer.createText(this._el_58,'\n							',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'span',(null as any));
    this._NgSwitch_60_3 = new import18.NgSwitch();
    this._text_61 = this.renderer.createText(this._el_60,'\n								',(null as any));
    this._anchor_62 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_62 = new import2.AppElement(62,60,this,this._anchor_62);
    this._TemplateRef_62_5 = new import15.TemplateRef_(this._appEl_62,viewFactory_JobListComponent8);
    this._NgSwitchCase_62_6 = new import18.NgSwitchCase(this._appEl_62.vcRef,this._TemplateRef_62_5,this._NgSwitch_60_3);
    this._text_63 = this.renderer.createText(this._el_60,'\n\n								',(null as any));
    this._anchor_64 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_64 = new import2.AppElement(64,60,this,this._anchor_64);
    this._TemplateRef_64_5 = new import15.TemplateRef_(this._appEl_64,viewFactory_JobListComponent9);
    this._NgSwitchCase_64_6 = new import18.NgSwitchCase(this._appEl_64.vcRef,this._TemplateRef_64_5,this._NgSwitch_60_3);
    this._text_65 = this.renderer.createText(this._el_60,'\n\n								',(null as any));
    this._anchor_66 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_66 = new import2.AppElement(66,60,this,this._anchor_66);
    this._TemplateRef_66_5 = new import15.TemplateRef_(this._appEl_66,viewFactory_JobListComponent10);
    this._NgSwitchCase_66_6 = new import18.NgSwitchCase(this._appEl_66.vcRef,this._TemplateRef_66_5,this._NgSwitch_60_3);
    this._text_67 = this.renderer.createText(this._el_60,'\n\n								',(null as any));
    this._anchor_68 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_68 = new import2.AppElement(68,60,this,this._anchor_68);
    this._TemplateRef_68_5 = new import15.TemplateRef_(this._appEl_68,viewFactory_JobListComponent11);
    this._NgSwitchCase_68_6 = new import18.NgSwitchCase(this._appEl_68.vcRef,this._TemplateRef_68_5,this._NgSwitch_60_3);
    this._text_69 = this.renderer.createText(this._el_60,'\n\n								',(null as any));
    this._anchor_70 = this.renderer.createTemplateAnchor(this._el_60,(null as any));
    this._appEl_70 = new import2.AppElement(70,60,this,this._anchor_70);
    this._TemplateRef_70_5 = new import15.TemplateRef_(this._appEl_70,viewFactory_JobListComponent12);
    this._NgSwitchDefault_70_6 = new import18.NgSwitchDefault(this._appEl_70.vcRef,this._TemplateRef_70_5,this._NgSwitch_60_3);
    this._text_71 = this.renderer.createText(this._el_60,'\n							',(null as any));
    this._text_72 = this.renderer.createText(this._el_58,'\n							',(null as any));
    this._text_73 = this.renderer.createText(this._el_53,'\n						',(null as any));
    this._text_74 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._text_75 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._pipe_timestampFormat_0_0 = import4.pureProxy1((<_View_JobListComponent0>this.parent.parent)._pipe_timestampFormat_0.transform.bind((<_View_JobListComponent0>this.parent.parent)._pipe_timestampFormat_0));
    this._expr_4 = import7.UNINITIALIZED;
    this._pipe_timestampFormat_0_1 = import4.pureProxy1((<_View_JobListComponent0>this.parent.parent)._pipe_timestampFormat_0.transform.bind((<_View_JobListComponent0>this.parent.parent)._pipe_timestampFormat_0));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._anchor_41,
      this._text_42,
      this._anchor_43,
      this._text_44,
      this._anchor_45,
      this._text_46,
      this._anchor_47,
      this._text_48,
      this._anchor_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._anchor_62,
      this._text_63,
      this._anchor_64,
      this._text_65,
      this._anchor_66,
      this._text_67,
      this._anchor_68,
      this._text_69,
      this._anchor_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (41 === requestNodeIndex))) { return this._TemplateRef_41_5; }
    if (((token === import18.NgSwitchCase) && (41 === requestNodeIndex))) { return this._NgSwitchCase_41_6; }
    if (((token === import15.TemplateRef) && (43 === requestNodeIndex))) { return this._TemplateRef_43_5; }
    if (((token === import18.NgSwitchCase) && (43 === requestNodeIndex))) { return this._NgSwitchCase_43_6; }
    if (((token === import15.TemplateRef) && (45 === requestNodeIndex))) { return this._TemplateRef_45_5; }
    if (((token === import18.NgSwitchCase) && (45 === requestNodeIndex))) { return this._NgSwitchCase_45_6; }
    if (((token === import15.TemplateRef) && (47 === requestNodeIndex))) { return this._TemplateRef_47_5; }
    if (((token === import18.NgSwitchCase) && (47 === requestNodeIndex))) { return this._NgSwitchCase_47_6; }
    if (((token === import15.TemplateRef) && (49 === requestNodeIndex))) { return this._TemplateRef_49_5; }
    if (((token === import18.NgSwitchDefault) && (49 === requestNodeIndex))) { return this._NgSwitchDefault_49_6; }
    if (((token === import18.NgSwitch) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._NgSwitch_39_3; }
    if (((token === import15.TemplateRef) && (62 === requestNodeIndex))) { return this._TemplateRef_62_5; }
    if (((token === import18.NgSwitchCase) && (62 === requestNodeIndex))) { return this._NgSwitchCase_62_6; }
    if (((token === import15.TemplateRef) && (64 === requestNodeIndex))) { return this._TemplateRef_64_5; }
    if (((token === import18.NgSwitchCase) && (64 === requestNodeIndex))) { return this._NgSwitchCase_64_6; }
    if (((token === import15.TemplateRef) && (66 === requestNodeIndex))) { return this._TemplateRef_66_5; }
    if (((token === import18.NgSwitchCase) && (66 === requestNodeIndex))) { return this._NgSwitchCase_66_6; }
    if (((token === import15.TemplateRef) && (68 === requestNodeIndex))) { return this._TemplateRef_68_5; }
    if (((token === import18.NgSwitchCase) && (68 === requestNodeIndex))) { return this._NgSwitchCase_68_6; }
    if (((token === import15.TemplateRef) && (70 === requestNodeIndex))) { return this._TemplateRef_70_5; }
    if (((token === import18.NgSwitchDefault) && (70 === requestNodeIndex))) { return this._NgSwitchDefault_70_6; }
    if (((token === import18.NgSwitch) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._NgSwitch_60_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_7:any = ((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.status);
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgSwitch_39_3.ngSwitch = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = 'onqueue';
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgSwitchCase_41_6.ngSwitchCase = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = 'running';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgSwitchCase_43_6.ngSwitchCase = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = 'success';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgSwitchCase_45_6.ngSwitchCase = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = 'error';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgSwitchCase_47_6.ngSwitchCase = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.$implicit.status;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgSwitch_60_3.ngSwitch = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = 'onqueue';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgSwitchCase_62_6.ngSwitchCase = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 'success';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgSwitchCase_64_6.ngSwitchCase = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = 'running';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgSwitchCase_66_6.ngSwitchCase = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = 'error';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgSwitchCase_68_6.ngSwitchCase = currVal_16;
      this._expr_16 = currVal_16;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'job-row-',this.context.$implicit.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'id',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.task.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_5,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,' ',this.context.$implicit.id,'\n						');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_14,currVal_3);
      this._expr_3 = currVal_3;
    }
    valUnwrapper.reset();
    const currVal_4:any = import4.interpolate(1,' ',valUnwrapper.unwrap(import4.castByValue(this._pipe_timestampFormat_0_0,(<_View_JobListComponent0>this.parent.parent)._pipe_timestampFormat_0.transform)(this.context.$implicit.createdAt)),'\n						');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_4,currVal_4))) {
      this.renderer.setText(this._text_20,currVal_4);
      this._expr_4 = currVal_4;
    }
    valUnwrapper.reset();
    const currVal_5:any = import4.interpolate(1,' ',valUnwrapper.unwrap(import4.castByValue(this._pipe_timestampFormat_0_1,(<_View_JobListComponent0>this.parent.parent)._pipe_timestampFormat_0.transform)(this.context.$implicit.startedAt)),'\n						');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_5,currVal_5))) {
      this.renderer.setText(this._text_26,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,' ',this.context.$implicit.duration,'s\n						');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_32,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.view(this.context.$implicit.projectId,this.context.$implicit.taskId)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_JobListComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent3,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label label-primary');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.status,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent4,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label label-warning');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.status,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent5,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label label-success');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.status,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent6,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label label-danger');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.status,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent7,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label label-success');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.status,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent8,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-valuemax','100');
    this.renderer.setElementAttribute(this._el_0,'aria-valuemin','0');
    this.renderer.setElementAttribute(this._el_0,'class','active progress-bar progress-bar-info');
    this.renderer.setElementAttribute(this._el_0,'role','progressbar');
    this.renderer.setElementAttribute(this._el_0,'style','min-width: 2em');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.progress;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_0,'aria-valuenow',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.$implicit.progress + '%');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n									',this.parent.context.$implicit.progress,'%\n								');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent9,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-valuemax','100');
    this.renderer.setElementAttribute(this._el_0,'aria-valuemin','0');
    this.renderer.setElementAttribute(this._el_0,'class','active progress-bar progress-bar-success');
    this.renderer.setElementAttribute(this._el_0,'role','progressbar');
    this.renderer.setElementAttribute(this._el_0,'style','min-width: 2em');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.progress;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_0,'aria-valuenow',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.$implicit.progress + '%');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n									',this.parent.context.$implicit.progress,'%\n								');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent9(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent10 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent10,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-valuemax','100');
    this.renderer.setElementAttribute(this._el_0,'aria-valuemin','0');
    this.renderer.setElementAttribute(this._el_0,'class','active progress-bar progress-bar-striped progress-bar-warning');
    this.renderer.setElementAttribute(this._el_0,'role','progressbar');
    this.renderer.setElementAttribute(this._el_0,'style','min-width: 2em');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.progress;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_0,'aria-valuenow',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.$implicit.progress + '%');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n									',this.parent.context.$implicit.progress,'%\n								');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent10(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent10(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent11 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent11,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-valuemax','100');
    this.renderer.setElementAttribute(this._el_0,'aria-valuemin','0');
    this.renderer.setElementAttribute(this._el_0,'class','active progress-bar progress-bar-danger');
    this.renderer.setElementAttribute(this._el_0,'role','progressbar');
    this.renderer.setElementAttribute(this._el_0,'style','min-width: 2em');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.progress;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_0,'aria-valuenow',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.$implicit.progress + '%');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n									',this.parent.context.$implicit.progress,'%\n								');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent11(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent11(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent12 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent12,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'aria-valuemax','100');
    this.renderer.setElementAttribute(this._el_0,'aria-valuemin','0');
    this.renderer.setElementAttribute(this._el_0,'class','active progress-bar progress-bar-success');
    this.renderer.setElementAttribute(this._el_0,'role','progressbar');
    this.renderer.setElementAttribute(this._el_0,'style','min-width: 2em');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.$implicit.progress;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementAttribute(this._el_0,'aria-valuenow',((currVal_0 == (null as any))? (null as any): currVal_0.toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = (this.parent.context.$implicit.progress + '%');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n									',this.parent.context.$implicit.progress,'%\n								');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_JobListComponent12(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent12(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent13 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent13,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','no-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'No jobs found',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobListComponent13(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent13(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent14 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent14,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','error-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Problem while loading job list',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'p',(null as any));
    this.renderer.setElementAttribute(this._el_9,'id','error-data-message');
    this._text_10 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_11,'type','button');
    this._text_12 = this.renderer.createText(this._el_11,'Try again',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n		',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.load()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_JobListComponent14(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent14(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent15 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent15,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','loading-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'Loading...',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobListComponent15(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent15(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent16 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _BaseChartComponent_11_4:import20.BaseChartComponent;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent16,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','graph-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Job graph',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_11 = this.renderer.createElement(this._el_4,'base-chart',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','chart');
    this._appEl_11 = new import2.AppElement(11,4,this,this._el_11);
    var compView_11:any = import21.viewFactory_BaseChartComponent0(this.viewUtils,this.injector(11),this._appEl_11);
    this._BaseChartComponent_11_4 = new import20.BaseChartComponent(new import22.ElementRef(this._el_11));
    this._appEl_11.initComponent(this._BaseChartComponent_11_4,[],compView_11);
    this._text_12 = this.renderer.createText((null as any),'\n					',(null as any));
    compView_11.create(this._BaseChartComponent_11_4,[],(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.BaseChartComponent) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._BaseChartComponent_11_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.chartDataDatasets;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._BaseChartComponent_11_4.datasets = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['datasets'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.chartDataLabels;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._BaseChartComponent_11_4.labels = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['labels'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.chartDataOptions;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._BaseChartComponent_11_4.options = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['options'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'doughnut';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._BaseChartComponent_11_4.chartType = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['chartType'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.parent.context.chartDataColors;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._BaseChartComponent_11_4.colors = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['colors'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._BaseChartComponent_11_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._BaseChartComponent_11_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._BaseChartComponent_11_4.ngOnDestroy();
  }
}
function viewFactory_JobListComponent16(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent16(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent17 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent17,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','graph-no-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'No jobs for graph',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobListComponent17(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent17(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent18 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent18,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','graph-error-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'\n					',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Problem while loading job list',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobListComponent18(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent18(viewUtils,parentInjector,declarationEl);
}
class _View_JobListComponent19 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_JobListComponent19,renderType_JobListComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','graph-loading-data');
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','panel panel-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n				',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','panel-body');
    this._text_5 = this.renderer.createText(this._el_4,'Loading...',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_JobListComponent19(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_JobListComponent19(viewUtils,parentInjector,declarationEl);
}