/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['h4.list-group-item-heading[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n	text-decoration: none;\n	color: #000;\n}\n\nh4.list-group-item-heading[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:focus {\n	text-decoration: none;\n	color: #000;\n}\n\nh4.list-group-item-heading[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover {\n	text-decoration: none;\n	color: #6e6e6e;\n}'];