/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.home-index[_ngcontent-%COMP%]   .logo[_ngcontent-%COMP%] {\n	width: 200px;\n}\n\n.jumbotron[_ngcontent-%COMP%] {\n	text-align: center;\n	background-color: transparent;\n}\n\n.jumbotron[_ngcontent-%COMP%]   .btn[_ngcontent-%COMP%] {\n	font-size: 21px;\n	padding: 14px 24px;\n}'];