/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/home/home.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from './home.component.css.shim';
import * as import11 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import12 from '@angular/router/src/router';
import * as import13 from '@angular/router/src/router_state';
import * as import14 from '@angular/common/src/location/location_strategy';
import * as import15 from '@angular/router/src/directives/router_link';
export class Wrapper_HomeComponent {
  context:import0.HomeComponent;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.HomeComponent();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_HomeComponent_Host:import2.RenderComponentType = (null as any);
class _View_HomeComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HomeComponent_0_4:Wrapper_HomeComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent_Host0,renderType_HomeComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'home',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomeComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomeComponent_0_4 = new Wrapper_HomeComponent();
    this._appEl_0.initComponent(this._HomeComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HomeComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomeComponent) && (0 === requestNodeIndex))) { return this._HomeComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomeComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._HomeComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomeComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomeComponent_Host === (null as any))) { (renderType_HomeComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomeComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomeComponentNgFactory:import9.ComponentFactory<import0.HomeComponent> = new import9.ComponentFactory<import0.HomeComponent>('home',viewFactory_HomeComponent_Host0,import0.HomeComponent);
const styles_HomeComponent:any[] = [import10.styles];
var renderType_HomeComponent:import2.RenderComponentType = (null as any);
class _View_HomeComponent0 extends import1.AppView<import0.HomeComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _RouterLinkWithHref_17_3:import11.Wrapper_RouterLinkWithHref;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomeComponent0,renderType_HomeComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','home-index'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','jumbotron'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'h1',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'GoCI',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_2,'p',new import4.InlineArray2(2,'class','lead'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'img',new import4.InlineArray8(8,'alt','','border','0','class','logo','src','../../static/images/logo.png'),(null as any));
    this._text_10 = this.renderer.createText(this._el_7,'\n		',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_2,'p',new import4.InlineArray2(2,'class','lead'),(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Welcome! Click on button below to start!.',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n\n		',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_2,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n			',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_15,'a',new import4.InlineArray4(4,'class','btn btn-lg btn-success','routerLink','/project/list'),(null as any));
    this._RouterLinkWithHref_17_3 = new import11.Wrapper_RouterLinkWithHref(this.parentInjector.get(import12.Router),this.parentInjector.get(import13.ActivatedRoute),this.parentInjector.get(import14.LocationStrategy));
    this._text_18 = this.renderer.createText(this._el_17,'Start',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n		',(null as any));
    this._text_20 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','body-content'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'\n\n		',(null as any));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_22,'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_24,'div',new import4.InlineArray2(2,'class','col-lg-4'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_26,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Simple structure',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._el_31 = import4.createRenderElement(this.renderer,this._el_26,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'With a file based structure you can easily versioning all project files',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n			',(null as any));
    this._text_34 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_24,'div',new import4.InlineArray2(2,'class','col-lg-4'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'\n				',(null as any));
    this._el_37 = import4.createRenderElement(this.renderer,this._el_35,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Simple API',(null as any));
    this._text_39 = this.renderer.createText(this._el_35,'\n				',(null as any));
    this._el_40 = import4.createRenderElement(this.renderer,this._el_35,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'It works with a simple API, using HTTP requests to make everything - if you want',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n			',(null as any));
    this._text_43 = this.renderer.createText(this._el_24,'\n			',(null as any));
    this._el_44 = import4.createRenderElement(this.renderer,this._el_24,'div',new import4.InlineArray2(2,'class','col-lg-4'),(null as any));
    this._text_45 = this.renderer.createText(this._el_44,'\n				',(null as any));
    this._el_46 = import4.createRenderElement(this.renderer,this._el_44,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Friendly Interface',(null as any));
    this._text_48 = this.renderer.createText(this._el_44,'\n				',(null as any));
    this._el_49 = import4.createRenderElement(this.renderer,this._el_44,'p',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'You can see your logs with a nice and friendly web responsive interface',(null as any));
    this._text_51 = this.renderer.createText(this._el_44,'\n			',(null as any));
    this._text_52 = this.renderer.createText(this._el_24,'\n		',(null as any));
    this._text_53 = this.renderer.createText(this._el_22,'\n\n	',(null as any));
    this._text_54 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.RouterLinkWithHref) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkWithHref_17_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_17_0_0:any = '/project/list';
    this._RouterLinkWithHref_17_3.check_routerLink(currVal_17_0_0,throwOnChange,false);
    this._RouterLinkWithHref_17_3.detectChangesInInputProps(this,this._el_17,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_17_3.detectChangesInHostProps(this,this._el_17,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_17_3.context.ngOnDestroy();
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_17_0:any = ((<any>this._RouterLinkWithHref_17_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_17_0);
  }
}
export function viewFactory_HomeComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HomeComponent> {
  if ((renderType_HomeComponent === (null as any))) { (renderType_HomeComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.Emulated,styles_HomeComponent,{})); }
  return new _View_HomeComponent0(viewUtils,parentInjector,declarationEl);
}