/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../src/app/app-main/app-main.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../src/app/services/GlobalService';
import * as import9 from '../../../../src/app/services/JobService';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../../../src/app/app-header/app-header.component';
import * as import13 from '@angular/router/src/directives/router_outlet';
import * as import14 from '../../../../src/app/app-footer/app-footer.component';
import * as import15 from '../app-header/app-header.component.ngfactory';
import * as import16 from '@angular/router/src/router_outlet_map';
import * as import17 from '@angular/core/src/linker/component_factory_resolver';
import * as import18 from '../app-footer/app-footer.component.ngfactory';
var renderType_AppMainComponent_Host:import0.RenderComponentType = (null as any);
class _View_AppMainComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AppMainComponent_0_4:import3.AppMainComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppMainComponent_Host0,renderType_AppMainComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-main',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppMainComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppMainComponent_0_4 = new import3.AppMainComponent(this.parentInjector.get(import8.GlobalService),this.parentInjector.get(import9.JobService));
    this._appEl_0.initComponent(this._AppMainComponent_0_4,[],compView_0);
    compView_0.create(this._AppMainComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AppMainComponent) && (0 === requestNodeIndex))) { return this._AppMainComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AppMainComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppMainComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AppMainComponent_Host === (null as any))) { (renderType_AppMainComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_AppMainComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppMainComponentNgFactory:import11.ComponentFactory<import3.AppMainComponent> = new import11.ComponentFactory<import3.AppMainComponent>('app-main',viewFactory_AppMainComponent_Host0,import3.AppMainComponent);
const styles_AppMainComponent:any[] = [];
var renderType_AppMainComponent:import0.RenderComponentType = (null as any);
class _View_AppMainComponent0 extends import1.AppView<import3.AppMainComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _AppHeaderComponent_2_4:import12.AppHeaderComponent;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _RouterOutlet_6_5:import13.RouterOutlet;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _AppFooterComponent_10_4:import14.AppFooterComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppMainComponent0,renderType_AppMainComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','wrap');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'app-header',(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_AppHeaderComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._AppHeaderComponent_2_4 = new import12.AppHeaderComponent(this.parentInjector.get(import8.GlobalService));
    this._appEl_2.initComponent(this._AppHeaderComponent_2_4,[],compView_2);
    compView_2.create(this._AppHeaderComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','container');
    this._text_5 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'router-outlet',(null as any));
    this._appEl_6 = new import2.AppElement(6,4,this,this._el_6);
    this._RouterOutlet_6_5 = new import13.RouterOutlet(this.parentInjector.get(import16.RouterOutletMap),this._appEl_6.vcRef,this.parentInjector.get(import17.ComponentFactoryResolver),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n	',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'app-footer',(null as any));
    this._appEl_10 = new import2.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import18.viewFactory_AppFooterComponent0(this.viewUtils,this.injector(10),this._appEl_10);
    this._AppFooterComponent_10_4 = new import14.AppFooterComponent();
    this._appEl_10.initComponent(this._AppFooterComponent_10_4,[],compView_10);
    compView_10.create(this._AppFooterComponent_10_4,[],(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.AppHeaderComponent) && (2 === requestNodeIndex))) { return this._AppHeaderComponent_2_4; }
    if (((token === import13.RouterOutlet) && (6 === requestNodeIndex))) { return this._RouterOutlet_6_5; }
    if (((token === import14.AppFooterComponent) && (10 === requestNodeIndex))) { return this._AppFooterComponent_10_4; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._RouterOutlet_6_5.ngOnDestroy();
  }
}
export function viewFactory_AppMainComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AppMainComponent> {
  if ((renderType_AppMainComponent === (null as any))) { (renderType_AppMainComponent = viewUtils.createRenderComponentType('/Users/paulo/Documents/workspaces/go/src/github.com/prsolucoes/goci/web-app/src/app/app-main/app-main.component.html',0,import10.ViewEncapsulation.None,styles_AppMainComponent,{})); }
  return new _View_AppMainComponent0(viewUtils,parentInjector,declarationEl);
}