/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../src/app/not-found/not-found.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_NotFoundComponent_Host:import0.RenderComponentType = (null as any);
class _View_NotFoundComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NotFoundComponent_0_4:import3.NotFoundComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NotFoundComponent_Host0,renderType_NotFoundComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('not-found',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NotFoundComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NotFoundComponent_0_4 = new import3.NotFoundComponent();
    this._appEl_0.initComponent(this._NotFoundComponent_0_4,[],compView_0);
    compView_0.create(this._NotFoundComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.NotFoundComponent) && (0 === requestNodeIndex))) { return this._NotFoundComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_NotFoundComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_NotFoundComponent_Host === (null as any))) { (renderType_NotFoundComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_NotFoundComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NotFoundComponentNgFactory:import9.ComponentFactory<import3.NotFoundComponent> = new import9.ComponentFactory<import3.NotFoundComponent>('not-found',viewFactory_NotFoundComponent_Host0,import3.NotFoundComponent);
const styles_NotFoundComponent:any[] = [];
var renderType_NotFoundComponent:import0.RenderComponentType = (null as any);
class _View_NotFoundComponent0 extends import1.AppView<import3.NotFoundComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_NotFoundComponent0,renderType_NotFoundComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'style','width: 100%; text-align: center;');
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h1',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		Oops!',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n		404 Not Found',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','error-details');
    this._text_9 = this.renderer.createText(this._el_8,'\n		Sorry, an error has occured, Requested page not found!\n	',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_NotFoundComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.NotFoundComponent> {
  if ((renderType_NotFoundComponent === (null as any))) { (renderType_NotFoundComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_NotFoundComponent,{})); }
  return new _View_NotFoundComponent0(viewUtils,parentInjector,declarationEl);
}