/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/app-header/app-header.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../src/app/services/GlobalService';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from './app-header.component.css.shim';
import * as import12 from '../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/router/src/directives/router_link';
export class Wrapper_AppHeaderComponent {
  context:import0.AppHeaderComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.AppHeaderComponent(p0);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppHeaderComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppHeaderComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppHeaderComponent_0_4:Wrapper_AppHeaderComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppHeaderComponent_Host0,renderType_AppHeaderComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'app-header',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppHeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppHeaderComponent_0_4 = new Wrapper_AppHeaderComponent(this.parentInjector.get(import8.GlobalService));
    this._appEl_0.initComponent(this._AppHeaderComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppHeaderComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppHeaderComponent) && (0 === requestNodeIndex))) { return this._AppHeaderComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppHeaderComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppHeaderComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppHeaderComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppHeaderComponent_Host === (null as any))) { (renderType_AppHeaderComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppHeaderComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppHeaderComponentNgFactory:import10.ComponentFactory<import0.AppHeaderComponent> = new import10.ComponentFactory<import0.AppHeaderComponent>('app-header',viewFactory_AppHeaderComponent_Host0,import0.AppHeaderComponent);
const styles_AppHeaderComponent:any[] = [import11.styles];
var renderType_AppHeaderComponent:import2.RenderComponentType = (null as any);
class _View_AppHeaderComponent0 extends import1.AppView<import0.AppHeaderComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _RouterLinkWithHref_18_3:import12.Wrapper_RouterLinkWithHref;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _RouterLinkWithHref_30_3:import12.Wrapper_RouterLinkWithHref;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _RouterLinkWithHref_42_3:import12.Wrapper_RouterLinkWithHref;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  /*private*/ _expr_52:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppHeaderComponent0,renderType_AppHeaderComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_52 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'nav',new import4.InlineArray2(2,'class','navbar navbar-default navbar-fixed-top'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','container-fluid'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'button',new import4.InlineArray16(12,'aria-controls','navbar','aria-expanded','false','class','navbar-toggle collapsed','data-target','#nav-collapse','data-toggle','collapse','type','button'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'span',new import4.InlineArray2(2,'class','sr-only'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Toggle navigation',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_6,'span',new import4.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_6,'span',new import4.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_14 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_6,'span',new import4.InlineArray2(2,'class','icon-bar'),(null as any));
    this._text_16 = this.renderer.createText(this._el_6,'\n			',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_4,'a',new import4.InlineArray8(6,'class','navbar-brand','href','javascript: void(0);','routerLink','/home'),(null as any));
    this._RouterLinkWithHref_18_3 = new import12.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_19 = this.renderer.createText(this._el_18,'\n				',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_18,'img',new import4.InlineArray8(8,'alt','','border','0','class','logo pull-left','src','../../static/images/logo-header.png'),(null as any));
    this._text_21 = this.renderer.createText(this._el_18,'\n				GoCI\n			',(null as any));
    this._text_22 = this.renderer.createText(this._el_4,'\n		',(null as any));
    this._text_23 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray4(4,'class','collapse navbar-collapse','id','nav-collapse'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'\n\n			',(null as any));
    this._el_26 = import4.createRenderElement(this.renderer,this._el_24,'ul',new import4.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_26,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'\n					',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_28,'a',new import4.InlineArray4(4,'href','javascript: void(0);','routerLink','/job/list'),(null as any));
    this._RouterLinkWithHref_30_3 = new import12.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_31 = this.renderer.createText(this._el_30,'\n						',(null as any));
    this._el_32 = import4.createRenderElement(this.renderer,this._el_30,'span',new import4.InlineArray2(2,'class','ph-job-running-list-count'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n						',(null as any));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_30,'span',new import4.InlineArray2(2,'class','ph-job-running-list-text'),(null as any));
    this._text_36 = this.renderer.createText(this._el_35,'jobs',(null as any));
    this._text_37 = this.renderer.createText(this._el_30,'\n					',(null as any));
    this._text_38 = this.renderer.createText(this._el_28,'\n				',(null as any));
    this._text_39 = this.renderer.createText(this._el_26,'\n				',(null as any));
    this._el_40 = import4.createRenderElement(this.renderer,this._el_26,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'\n					',(null as any));
    this._el_42 = import4.createRenderElement(this.renderer,this._el_40,'a',new import4.InlineArray4(4,'href','javascript: void(0);','routerLink','/home'),(null as any));
    this._RouterLinkWithHref_42_3 = new import12.Wrapper_RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_43 = this.renderer.createText(this._el_42,'Home',(null as any));
    this._text_44 = this.renderer.createText(this._el_40,'\n				',(null as any));
    this._text_45 = this.renderer.createText(this._el_26,'\n			',(null as any));
    this._text_46 = this.renderer.createText(this._el_24,'\n\n		',(null as any));
    this._text_47 = this.renderer.createText(this._el_2,'\n	',(null as any));
    this._text_48 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_18,'click',this.eventHandler(this._handle_click_18_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.RouterLinkWithHref) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_18_3.context; }
    if (((token === import16.RouterLinkWithHref) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._RouterLinkWithHref_30_3.context; }
    if (((token === import16.RouterLinkWithHref) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._RouterLinkWithHref_42_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_18_0_0:any = '/home';
    this._RouterLinkWithHref_18_3.check_routerLink(currVal_18_0_0,throwOnChange,false);
    this._RouterLinkWithHref_18_3.detectChangesInInputProps(this,this._el_18,throwOnChange);
    const currVal_30_0_0:any = '/job/list';
    this._RouterLinkWithHref_30_3.check_routerLink(currVal_30_0_0,throwOnChange,false);
    this._RouterLinkWithHref_30_3.detectChangesInInputProps(this,this._el_30,throwOnChange);
    const currVal_42_0_0:any = '/home';
    this._RouterLinkWithHref_42_3.check_routerLink(currVal_42_0_0,throwOnChange,false);
    this._RouterLinkWithHref_42_3.detectChangesInInputProps(this,this._el_42,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_18_3.detectChangesInHostProps(this,this._el_18,throwOnChange);
    this._RouterLinkWithHref_30_3.detectChangesInHostProps(this,this._el_30,throwOnChange);
    const currVal_52:any = import4.interpolate(1,'',this.context.jobs,'');
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setText(this._text_33,currVal_52);
      this._expr_52 = currVal_52;
    }
    this._RouterLinkWithHref_42_3.detectChangesInHostProps(this,this._el_42,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_18_3.context.ngOnDestroy();
    this._RouterLinkWithHref_30_3.context.ngOnDestroy();
    this._RouterLinkWithHref_42_3.context.ngOnDestroy();
  }
  private _handle_click_18_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_18_0:any = ((<any>this._RouterLinkWithHref_18_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_18_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_30_0:any = ((<any>this._RouterLinkWithHref_30_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_30_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_42_0:any = ((<any>this._RouterLinkWithHref_42_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_42_0);
  }
}
export function viewFactory_AppHeaderComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppHeaderComponent> {
  if ((renderType_AppHeaderComponent === (null as any))) { (renderType_AppHeaderComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.Emulated,styles_AppHeaderComponent,{})); }
  return new _View_AppHeaderComponent0(viewUtils,parentInjector,declarationEl);
}