/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../src/app/project-view/project-view.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../../src/app/services/GlobalService';
import * as import9 from '../../../../src/app/services/ProjectService';
import * as import10 from '../../../../src/app/services/TaskService';
import * as import11 from '@angular/router/src/router';
import * as import12 from '@angular/router/src/router_state';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '@angular/core/src/linker/template_ref';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '../project-task-item/project-task-item.component.ngfactory';
import * as import22 from '../../../../src/app/project-task-item/project-task-item.component';
import * as import23 from '../task-options/task-options.component.ngfactory';
import * as import24 from '../../../../src/app/task-options/task-options.component';
export class Wrapper_ProjectViewComponent {
  context:import0.ProjectViewComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.ProjectViewComponent(p0,p1,p2,p3,p4);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_ProjectViewComponent_Host:import2.RenderComponentType = (null as any);
class _View_ProjectViewComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ProjectViewComponent_0_4:Wrapper_ProjectViewComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent_Host0,renderType_ProjectViewComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'project-view',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProjectViewComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProjectViewComponent_0_4 = new Wrapper_ProjectViewComponent(this.parentInjector.get(import8.GlobalService),this.parentInjector.get(import9.ProjectService),this.parentInjector.get(import10.TaskService),this.parentInjector.get(import11.Router),this.parentInjector.get(import12.ActivatedRoute));
    this._appEl_0.initComponent(this._ProjectViewComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ProjectViewComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProjectViewComponent) && (0 === requestNodeIndex))) { return this._ProjectViewComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProjectViewComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._ProjectViewComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProjectViewComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ProjectViewComponent_Host === (null as any))) { (renderType_ProjectViewComponent_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ProjectViewComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProjectViewComponentNgFactory:import14.ComponentFactory<import0.ProjectViewComponent> = new import14.ComponentFactory<import0.ProjectViewComponent>('project-view',viewFactory_ProjectViewComponent_Host0,import0.ProjectViewComponent);
const styles_ProjectViewComponent:any[] = ([] as any[]);
var renderType_ProjectViewComponent:import2.RenderComponentType = (null as any);
class _View_ProjectViewComponent0 extends import1.AppView<import0.ProjectViewComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import15.Wrapper_NgIf;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import15.Wrapper_NgIf;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import15.Wrapper_NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import15.Wrapper_NgIf;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import15.Wrapper_NgIf;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_45:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent0,renderType_ProjectViewComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_45 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','project-view'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._text_2 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray4(4,'class','panel panel-default','id','options-container'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n		',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'div',new import4.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'h3',new import4.InlineArray2(2,'class','options-container-title'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_5,'button',new import4.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Refresh',(null as any));
    this._text_12 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_5,'button',new import4.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Back',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n	',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_19 = new import3.AppElement(19,0,this,this._anchor_19);
    this._TemplateRef_19_5 = new import16.TemplateRef_(this._appEl_19,viewFactory_ProjectViewComponent1);
    this._NgIf_19_6 = new import15.Wrapper_NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_21 = new import3.AppElement(21,0,this,this._anchor_21);
    this._TemplateRef_21_5 = new import16.TemplateRef_(this._appEl_21,viewFactory_ProjectViewComponent5);
    this._NgIf_21_6 = new import15.Wrapper_NgIf(this._appEl_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_23 = new import3.AppElement(23,0,this,this._anchor_23);
    this._TemplateRef_23_5 = new import16.TemplateRef_(this._appEl_23,viewFactory_ProjectViewComponent6);
    this._NgIf_23_6 = new import15.Wrapper_NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_25 = new import3.AppElement(25,0,this,this._anchor_25);
    this._TemplateRef_25_5 = new import16.TemplateRef_(this._appEl_25,viewFactory_ProjectViewComponent7);
    this._NgIf_25_6 = new import15.Wrapper_NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_0,'\n\n	',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_27 = new import3.AppElement(27,0,this,this._anchor_27);
    this._TemplateRef_27_5 = new import16.TemplateRef_(this._appEl_27,viewFactory_ProjectViewComponent8);
    this._NgIf_27_6 = new import15.Wrapper_NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import17.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6.context; }
    if (((token === import16.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import17.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    if (((token === import16.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import17.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import16.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import17.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6.context; }
    if (((token === import16.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import17.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_19_0_0:any = this.context.showData;
    this._NgIf_19_6.check_ngIf(currVal_19_0_0,throwOnChange,false);
    this._NgIf_19_6.detectChangesInInputProps(this,this._anchor_19,throwOnChange);
    const currVal_21_0_0:any = this.context.showEmptyData;
    this._NgIf_21_6.check_ngIf(currVal_21_0_0,throwOnChange,false);
    this._NgIf_21_6.detectChangesInInputProps(this,this._anchor_21,throwOnChange);
    const currVal_23_0_0:any = this.context.showError;
    this._NgIf_23_6.check_ngIf(currVal_23_0_0,throwOnChange,false);
    this._NgIf_23_6.detectChangesInInputProps(this,this._anchor_23,throwOnChange);
    const currVal_25_0_0:any = this.context.showLoading;
    this._NgIf_25_6.check_ngIf(currVal_25_0_0,throwOnChange,false);
    this._NgIf_25_6.detectChangesInInputProps(this,this._anchor_25,throwOnChange);
    const currVal_27_0_0:any = this.context.showTaskOptionsForm;
    this._NgIf_27_6.check_ngIf(currVal_27_0_0,throwOnChange,false);
    this._NgIf_27_6.detectChangesInInputProps(this,this._anchor_27,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_45:any = import4.interpolate(1,'Project ',((this.context.project == (null as any))? (null as any): this.context.project.name),'');
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setText(this._text_8,currVal_45);
      this._expr_45 = currVal_45;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_10_0:any = ((<any>this.context.load()) !== false);
    return (true && pd_10_0);
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_13_0:any = ((<any>this.context.back()) !== false);
    return (true && pd_13_0);
  }
}
export function viewFactory_ProjectViewComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ProjectViewComponent> {
  if ((renderType_ProjectViewComponent === (null as any))) { (renderType_ProjectViewComponent = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ProjectViewComponent,{})); }
  return new _View_ProjectViewComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _anchor_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _TemplateRef_26_5:any;
  _NgIf_26_6:import15.Wrapper_NgIf;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import15.Wrapper_NgIf;
  _text_29:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent1,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'id','data'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'h5',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Details',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n\n		',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n			',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_9,'strong',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Name:',(null as any));
    this._text_12 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_7,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_14,'strong',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Description:',(null as any));
    this._text_17 = this.renderer.createText(this._el_14,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n				',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_7,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_19,'strong',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Tasks:',(null as any));
    this._text_22 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_23 = this.renderer.createText(this._el_7,'\n			',(null as any));
    this._text_24 = this.renderer.createText(this._el_5,'\n		',(null as any));
    this._text_25 = this.renderer.createText(this._el_0,'\n\n		',(null as any));
    this._anchor_26 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_26 = new import3.AppElement(26,0,this,this._anchor_26);
    this._TemplateRef_26_5 = new import16.TemplateRef_(this._appEl_26,viewFactory_ProjectViewComponent2);
    this._NgIf_26_6 = new import15.Wrapper_NgIf(this._appEl_26.vcRef,this._TemplateRef_26_5);
    this._text_27 = this.renderer.createText(this._el_0,'\n\n		',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_28 = new import3.AppElement(28,0,this,this._anchor_28);
    this._TemplateRef_28_5 = new import16.TemplateRef_(this._appEl_28,viewFactory_ProjectViewComponent3);
    this._NgIf_28_6 = new import15.Wrapper_NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._anchor_26,
      this._text_27,
      this._anchor_28,
      this._text_29
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (26 === requestNodeIndex))) { return this._TemplateRef_26_5; }
    if (((token === import17.NgIf) && (26 === requestNodeIndex))) { return this._NgIf_26_6.context; }
    if (((token === import16.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import17.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_26_0_0:any = (((this.parent.context.project.tasks == (null as any))? (null as any): this.parent.context.project.tasks.length) > 0);
    this._NgIf_26_6.check_ngIf(currVal_26_0_0,throwOnChange,false);
    this._NgIf_26_6.detectChangesInInputProps(this,this._anchor_26,throwOnChange);
    const currVal_28_0_0:any = (((this.parent.context.project.tasks == (null as any))? (null as any): this.parent.context.project.tasks.length) > 0);
    this._NgIf_28_6.check_ngIf(currVal_28_0_0,throwOnChange,false);
    this._NgIf_28_6.detectChangesInInputProps(this,this._anchor_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_36:any = import4.interpolate(1,' ',this.parent.context.project.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setText(this._text_12,currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = import4.interpolate(1,' ',this.parent.context.project.description,'');
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setText(this._text_17,currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = import4.interpolate(1,' ',((this.parent.context.project.tasks == (null as any))? (null as any): this.parent.context.project.tasks.length),'');
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setText(this._text_22,currVal_38);
      this._expr_38 = currVal_38;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProjectViewComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent2,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'h5',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Tasks',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_ProjectViewComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import18.Wrapper_NgFor;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent3,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray4(4,'class','list-group','id','project-task-list'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n			',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import16.TemplateRef_(this._appEl_2,viewFactory_ProjectViewComponent4);
    this._NgFor_2_6 = new import18.Wrapper_NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parent.parentInjector.get(import19.IterableDiffers),this.parent.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import20.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parent.parent.context.project.tasks;
    this._NgFor_2_6.check_ngForOf(currVal_2_0_0,throwOnChange,false);
    this._NgFor_2_6.detectChangesInInputProps(this,this._anchor_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProjectViewComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _ProjectTaskItemComponent_2_4:import21.Wrapper_ProjectTaskItemComponent;
  _text_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent4,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'class','project-task-row list-group-item'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n				',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'project-task-item',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import21.viewFactory_ProjectTaskItemComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._ProjectTaskItemComponent_2_4 = new import21.Wrapper_ProjectTaskItemComponent(this.parent.parent.parent.parentInjector.get(import8.GlobalService),this.parent.parent.parent.parentInjector.get(import11.Router));
    this._appEl_2.initComponent(this._ProjectTaskItemComponent_2_4.context,([] as any[]),compView_2);
    compView_2.create(this._ProjectTaskItemComponent_2_4.context,([] as any[]),(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n			',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'showTaskOptions',this.eventHandler(this._handle_showTaskOptions_2_0.bind(this)));
    const subscription_0:any = this._ProjectTaskItemComponent_2_4.context.showTaskOptions.subscribe(this.eventHandler(this._handle_showTaskOptions_2_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.ProjectTaskItemComponent) && (2 === requestNodeIndex))) { return this._ProjectTaskItemComponent_2_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.parent.parent.parent.context.project;
    this._ProjectTaskItemComponent_2_4.check_project(currVal_2_0_0,throwOnChange,false);
    const currVal_2_0_1:any = this.context.$implicit;
    this._ProjectTaskItemComponent_2_4.check_task(currVal_2_0_1,throwOnChange,false);
    this._ProjectTaskItemComponent_2_4.detectChangesInInputProps(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._ProjectTaskItemComponent_2_4.detectChangesInHostProps(this,this._el_2,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_showTaskOptions_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_2_0:any = ((<any>this.parent.parent.parent.context.showTaskOptions($event)) !== false);
    return (true && pd_2_0);
  }
}
function viewFactory_ProjectViewComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent5,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'id','no-data'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Project not found',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_ProjectViewComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent6,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'id','error-data'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'h3',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Problem while loading project',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_4,'p',new import4.InlineArray2(2,'id','error-data-message'),(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n				',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_4,'button',new import4.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'Back',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n	',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_11_0:any = ((<any>this.parent.context.back()) !== false);
    return (true && pd_11_0);
  }
}
function viewFactory_ProjectViewComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent7,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'id','loading-data'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n		',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','panel panel-default'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n			',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Loading...',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_ProjectViewComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_ProjectViewComponent8 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _TaskOptionsComponent_0_4:import23.Wrapper_TaskOptionsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ProjectViewComponent8,renderType_ProjectViewComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'task-options',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import23.viewFactory_TaskOptionsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TaskOptionsComponent_0_4 = new import23.Wrapper_TaskOptionsComponent(this.parent.parentInjector.get(import10.TaskService));
    this._appEl_0.initComponent(this._TaskOptionsComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._TaskOptionsComponent_0_4.context,([] as any[]),(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'taskRunWithSuccess',this.eventHandler(this._handle_taskRunWithSuccess_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'taskRunWithError',this.eventHandler(this._handle_taskRunWithError_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'taskRunCancel',this.eventHandler(this._handle_taskRunCancel_0_2.bind(this)));
    const subscription_0:any = this._TaskOptionsComponent_0_4.context.taskRunWithSuccess.subscribe(this.eventHandler(this._handle_taskRunWithSuccess_0_0.bind(this)));
    const subscription_1:any = this._TaskOptionsComponent_0_4.context.taskRunWithError.subscribe(this.eventHandler(this._handle_taskRunWithError_0_1.bind(this)));
    const subscription_2:any = this._TaskOptionsComponent_0_4.context.taskRunCancel.subscribe(this.eventHandler(this._handle_taskRunCancel_0_2.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.TaskOptionsComponent) && (0 === requestNodeIndex))) { return this._TaskOptionsComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parent.context.runProjectId;
    this._TaskOptionsComponent_0_4.check_projectId(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = this.parent.context.runProjectName;
    this._TaskOptionsComponent_0_4.check_projectName(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = this.parent.context.runTaskId;
    this._TaskOptionsComponent_0_4.check_taskId(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.parent.context.runTaskName;
    this._TaskOptionsComponent_0_4.check_taskName(currVal_0_0_3,throwOnChange,false);
    const currVal_0_0_4:any = this.parent.context.runTaskDescription;
    this._TaskOptionsComponent_0_4.check_taskDescription(currVal_0_0_4,throwOnChange,false);
    const currVal_0_0_5:any = this.parent.context.runTaskOptions;
    this._TaskOptionsComponent_0_4.check_options(currVal_0_0_5,throwOnChange,false);
    this._TaskOptionsComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._TaskOptionsComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._TaskOptionsComponent_0_4.context.ngAfterViewInit(); } }
  }
  private _handle_taskRunWithSuccess_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this.parent.context.taskRunWithSuccess($event)) !== false);
    return (true && pd_0_0);
  }
  private _handle_taskRunWithError_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this.parent.context.taskRunWithError($event)) !== false);
    return (true && pd_0_0);
  }
  private _handle_taskRunCancel_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0_0:any = ((<any>this.parent.context.taskRunCancel($event)) !== false);
    return (true && pd_0_0);
  }
}
function viewFactory_ProjectViewComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ProjectViewComponent8(viewUtils,parentInjector,declarationEl);
}